name: PR action
on:
  pull_request:
    branches:
      - master
jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: detekt
        uses: natiginfo/action-detekt-all@1.20.0
        with:
          args: --config config/detekt/detekt.yml
      - name: tests
        run: |
          chmod +x ./gradlew
          ./gradlew testDebugUnitTest